In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("Dataset_WorldPortIndex.csv")
df.columns

Index(['Unnamed: 0', 'World Port Index Number', 'Region Name',
       'Main Port Name', 'Country Code', 'World Water Body',
       'Sailing Direction or Publication', 'Tidal Range (m)',
       'Channel Depth (m)', 'Anchorage Depth (m)', 'Cargo Pier Depth (m)',
       'Oil Terminal Depth (m)', 'Harbor Size', 'Harbor Type',
       'Shelter Afforded', 'Entrance Restriction - Tide',
       'Entrance Restriction - Heavy Swell', 'Entrance Restriction - Ice',
       'Entrance Restriction - Other', 'Overhead Limits',
       'Good Holding Ground', 'Communications - Telephone',
       'Communications - Radio', 'Communications - Radiotelephone',
       'Communications - Airport', 'Communications - Rail', 'NAVAREA',
       'Facilities - Wharves', 'Facilities - Anchorage', 'Medical Facilities',
       'Garbage Disposal', 'Dirty Ballast Disposal', 'Cranes - Mobile',
       'Lifts - 0-24 Tons', 'Services - Longshoremen', 'Supplies - Provisions',
       'Supplies - Potable Water', 'Supplies - Fuel Oil',
       'Supplies - Diesel Oil', 'Repairs', 'Latitude', 'Longitude'],
      dtype='object')

In [13]:
start_a = df["Main Port Name"].reset_index()
start_a[start_a["Main Port Name"].str.startswith("A")]

      index          Main Port Name
3         3                 Andoany
38       38             Aeroskobing
61       61   Al Khair Oil Terminal
75       75                   Adler
76       76         Arzew El Djedid
...     ...                     ...
3684   3684  Ash Shihr Oil Terminal
3719   3719         Arichat Harbour
3729   3729                  Avatiu
3743   3743                Altamira
3776   3776               Almirante

[190 rows x 2 columns]

In [ ]:
#Nazwa portu (Main Port Name) zaczyna się na literę "A".
df[df["Main Port Name"].str.startswith("A")].head(2)

,Unnamed: 0,World Port Index Number,Region Name,Main Port Name,Country Code,World Water Body,Sailing Direction or Publication,Tidal Range (m),Channel Depth (m),Anchorage Depth (m),...,Cranes - Mobile,Lifts - 0-24 Tons,Services - Longshoremen,Supplies - Provisions,Supplies - Potable Water,Supplies - Fuel Oil,Supplies - Diesel Oil,Repairs,Latitude,Longitude
3,3,47360.0,Madagascar -- 47350,Andoany,Madagascar,Mozambique Channel; Indian Ocean,Sailing Directions Pub. 171 (Enroute) - East A...,4.0,20.1,15.5,...,Yes,Yes,Yes,Unknown,Yes,No,No,Emergency Only,-13.400000,48.300000
38,38,29800.0,Aero -- 29780,Aeroskobing,Denmark,Baltic Sea; North Atlantic Ocean,Sailing Directions Pub. 194 (Enroute) - Baltic...,0.0,3.4,6.4,...,Unknown,Yes,Unknown,Yes,Yes,Yes,Yes,Limited,54.883333,10.416667

In [20]:
#Kod kraju (Country Code) to jeden z: ["United States", "Brunei", "Iran"].
lista_kodow = ["United States", "Brunei", "Iran"]
df[df["Country Code"].isin(lista_kodow)].head(5)

,Unnamed: 0,World Port Index Number,Region Name,Main Port Name,Country Code,World Water Body,Sailing Direction or Publication,Tidal Range (m),Channel Depth (m),Anchorage Depth (m),...,Cranes - Mobile,Lifts - 0-24 Tons,Services - Longshoremen,Supplies - Provisions,Supplies - Potable Water,Supplies - Fuel Oil,Supplies - Diesel Oil,Repairs,Latitude,Longitude
0,0,7950.0,United States E Coast -- 6585,Maurer,United States,North Atlantic Ocean,U.S. Coast Pilot 2 - Atlantic Coast: Cape Cod ...,1.5,11.0,11.0,...,Unknown,Unknown,Unknown,Yes,Yes,Yes,Yes,Moderate,40.533333,-74.250000
18,18,7010.0,United States E Coast -- 6585,New Harbor,United States,North Atlantic Ocean,U.S. Coast Pilot 1 - Atlantic Coast: Eastport ...,2.7,6.4,6.4,...,Unknown,Unknown,Unknown,Yes,Yes,Unknown,Yes,Limited,43.866667,-69.483333
21,21,4950.0,US Lake Michigan -- 4570,Depere,United States,Lake Michigan; Great Lakes,U.S. Coast Pilot 6 - Great Lakes and their con...,0.0,6.4,6.4,...,Unknown,Unknown,Unknown,Yes,Yes,Yes,Yes,Unknown,44.450000,-88.066667
22,22,4630.0,US Lake Michigan -- 4570,Leland,United States,Lake Michigan; Great Lakes,U.S. Coast Pilot 6 - Great Lakes and their con...,0.0,3.4,1.8,...,Unknown,Unknown,Unknown,Yes,Yes,Unknown,Yes,Unknown,45.016667,-85.766667
24,24,19880.0,Alaska -- 19080,Lazy Bay,United States,North Pacific Ocean,U.S. Coast Pilot 9 - Alaska: Cape Spencer to B...,2.7,23.2,15.5,...,Unknown,Unknown,No,Yes,Yes,No,Yes,Limited,56.900000,-154.250000

In [23]:
#Głębokość kanału (Channel Depth (m)) jest większa niż 10.
df[df["Channel Depth (m)"] > 10].head(2)

,Unnamed: 0,World Port Index Number,Region Name,Main Port Name,Country Code,World Water Body,Sailing Direction or Publication,Tidal Range (m),Channel Depth (m),Anchorage Depth (m),...,Cranes - Mobile,Lifts - 0-24 Tons,Services - Longshoremen,Supplies - Provisions,Supplies - Potable Water,Supplies - Fuel Oil,Supplies - Diesel Oil,Repairs,Latitude,Longitude
0,0,7950.0,United States E Coast -- 6585,Maurer,United States,North Atlantic Ocean,U.S. Coast Pilot 2 - Atlantic Coast: Cape Cod ...,1.5,11.0,11.0,...,Unknown,Unknown,Unknown,Yes,Yes,Yes,Yes,Moderate,40.533333,-74.25
2,2,47620.0,Madagascar -- 47350,Iharana,Madagascar,Indian Ocean,Sailing Directions Pub. 171 (Enroute) - East A...,8.0,14.0,14.0,...,Unknown,Unknown,Yes,Yes,Yes,No,No,Emergency Only,-13.350000,50.00

In [25]:

filtered_df = df[
    (df["Channel Depth (m)"] > 10) & 
    (df["Country Code"].isin(lista_kodow)) & 
    (df["Main Port Name"].str.startswith("A"))
]
filtered_df.head(3)

,Unnamed: 0,World Port Index Number,Region Name,Main Port Name,Country Code,World Water Body,Sailing Direction or Publication,Tidal Range (m),Channel Depth (m),Anchorage Depth (m),...,Cranes - Mobile,Lifts - 0-24 Tons,Services - Longshoremen,Supplies - Provisions,Supplies - Potable Water,Supplies - Fuel Oil,Supplies - Diesel Oil,Repairs,Latitude,Longitude
1078,1078,16850.0,United States W Coast -- 16000,Astoria,United States,North Pacific Ocean,U.S. Coast Pilot 10 - Oregon Washington Hawaii...,2.1,12.5,0.0,...,Unknown,Unknown,Yes,Yes,Yes,Yes,Yes,Moderate,46.200000,-123.833333
1215,1215,16330.0,United States W Coast -- 16000,Alameda,United States,North Pacific Ocean,U.S. Coast Pilot 7 - Pacific Coast: California,1.5,15.2,0.0,...,Yes,Unknown,Yes,Yes,Yes,Yes,Yes,Major,37.783333,-122.266667
1317,1317,18040.0,United States W Coast -- 16000,Anacortes,United States,Alaska-Canada coastal waters; North Pacific Ocean,U.S. Coast Pilot 10 - Oregon Washington Hawaii...,1.5,12.5,15.5,...,Yes,Unknown,Yes,Yes,Yes,Yes,Yes,Limited,48.516667,-122.616667

In [27]:
# Dodaj nową kolumnę Port Classification:

# "Deep Water" dla portów z Channel Depth (m) większą niż 15.
# "Moderate Water" dla portów z Channel Depth (m) między 10 a 15.
# "Shallow Water" dla portów z Channel Depth (m) mniejszą niż 10.

def get_depth(depth):
    if depth > 15:
        return "Deep Water"
    elif depth >=10 and depth <=15:
        return "Moderate Water"
    else:
        return "Shallow Water"

df["Port Classification"] = df["Channel Depth (m)"].apply(get_depth)

In [ ]:
import numpy as np

conditions = [
    df["Channel Depth (m)"] > 15,
    (df["Channel Depth (m)"] >= 10) & (df["Channel Depth (m)"] <= 15),
    df["Channel Depth (m)"] < 10
]
choices = ["Deep Water", "Moderate Water", "Shallow Water"]
df["Port Classification"] = np.select(conditions, choices)

In [34]:
#Dodaj nową kolumnę Coordinates, która połączy Latitude i Longitude w jeden string w formacie "(lat, lon)".
def get_coords(row):
    if not pd.isnull(row["Latitude"]) and not pd.isnull(row["Longitude"]):
        return f"({row['Latitude']}, {row['Longitude']})"
    else:
        return None

df["Coords"] = df.apply(get_coords, axis=1)

In [36]:
#"Country Code"
def get_port_type(code):
    if code == "United States":
        return "Domestic"
    else:
        return "International"

#two solutions - one with function, other with lambda    
df["Port Type"] = df["Country Code"].apply(lambda x: "Domestic" if x=="United States" else "International")

0            Domestic
1       International
2       International
3       International
4       International
            ...
3819    International
3820    International
3821    International
3822    International
3823    International
Name: Country Code, Length: 3824, dtype: object